name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    # Running on macOS as a workaround to https://github.com/paambaati/codeclimate-action/issues/275
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt
          pip install -r requirements-ci.txt
      - name: Lint with flake8
        run: |
          flake8 ./pinga
      - name: Run unit tests and generate coverage report
        run: |
          coverage run --source ./pinga -m pytest
          coverage report -m
          coverage xml -i -o coverage.xml
      - name: Publish code coverage report
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
