name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt
          pip install -r requirements-ci.txt
      - name: Lint with flake8
        run: |
          flake8 ./src
      - name: Run unit tests and generate coverage report
        run: |
          coverage run --source ./src -m pytest
          coverage report -m
          coverage xml -i -o coverage.xml
      - name: Publish code coverage report
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          # FIXME: This ID should be abstracted into a secret and not hardcoded here
          CC_TEST_REPORTER_ID: fbb02caaba945d0c6c7bf33428f6900c90af91a9a4b067aa506e4b39c812b4a5
